version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cinema
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema
      MYSQL_PASSWORD: cinema
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql