spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?useSSL=false&serverTimezone=UTC
    username: cinema
    password: cinema
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect